let title = "title";
let screens = 1;
let screenPrice = 2;
let rollback = 3;
let fullPrice = 11;
let adaptive = "adaptive";
alert ("Hello");
console.log ("Ok");

title = "The first project";
screens = "Простые, Сложные, Интерактивные";
screenPrice = 100;
fullPrice = 500;
adaptive = true;
console.log(typeof title);
console.log(typeof fullPrice);
console.log(typeof adaptive);
console.log(screens.length);
console.log("Стоимость верстки экранов " + screenPrice + " рублей"); 
console.log("Стоимость разработки сайта " + fullPrice + " рублей"); 
console.log(screens.toLowerCase(), screens.split(", "));
console.log("Процент отката посреднику за работу " + fullPrice*rollback/100);
